apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: istio
  namespace: istiosystem
spec:
  interval: 5m
  url: https://istio-release.storage.googleapis.com/charts
  chart:
    spec:
      chart: istio
      version: '1.20.0'
      sourceRef:
        kind: HelmRepository
        name: istio
      interval: 5m

