apiVersion: apps/v1
kind: Deployment
metadata:
  name: authority-app
  namespace: authority
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authority
  template:
    metadata:
      labels:
        app: authority
    spec:
      containers:
      - name: authority
        image: docker.io/12281404047/authority:latest
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: config-volume
          mountPath: "/app/kpf/enable-config"
      volumes:
      - name: config-volume
        configMap:
          name: authority-cm
