apiVersion: image.toolkit.fluxcd.io/v1alpha1
kind: ImageRepository
metadata:
  name: authority-app-harbor-repository
  namespace: flux-system
spec:
  image: harbor.cpt.ihk/cleverbit/authority
  interval: 1m
  secretRef:
    name: regcred