apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: authority-auto-update
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: flux-system
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        name: ihk_bot
        email: ihk_bot@example.com
      messageTemplate: 'Update image version to {{range .Updated.Images}}{{println .}}{{end}}'
    push:
      branch: main
  interval: 1m
  update:
    path: "./apps/authority"
    strategy: Setters