apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: authority-vs
  namespace: authority
spec:
  hosts:
  - "authority.cb-interview.com"
  gateways:
  - authority-gw
  https:
    route:
    - destination:
        host: authority-service
        port:
          name: https