apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: servicey-vs
  namespace: servicey
spec:
  hosts:
  - servicey.servicey.svc.cluster.local
  http:
  - route:
    - destination:
        host: servicey
        port:
          number: 8080