apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: servicex-vs
  namespace: servicex
spec:
  hosts:
  - "servicex.cb-interview.com"
  gateways:
  - servicex-gw
  http:
  - match:
    - uri:
        exact: /productpage
    route:
    - destination:
        host: servicex-service
        port:
          number: 8080